name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Bundler
        run:
          gem install bundler
      - name: Install Dependencies
        run:
          bundle install --without development production
      - name: Run Tests
        run:
          rails test
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "klima7-rails-toy-app"
          heroku_email: "ukasz.klimkiewicz@gmail.com"